# Generated by Django 4.1 on 2024-03-23 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.AlterField(
            model_name='creator',
            name='subscribers',
            field=models.ManyToManyField(related_name='publishers', to=settings.AUTH_USER_MODEL),
        ),
    ]
